# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 12:16
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import web_payments.translation


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20160323_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='amount_allocated',
        ),
        migrations.RemoveField(
            model_name='source',
            name='amount_debited',
        ),
        migrations.AddField(
            model_name='source',
            name='captured_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='source',
            name='extra_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='source',
            name='fraud_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='source',
            name='fraud_status',
            field=models.CharField(choices=[('unknown', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Unknown', None)), ('accept', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Passed', None)), ('reject', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Rejected', None)), ('review', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Review', None))], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='source',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='source',
            name='shipping_method_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('waiting', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Waiting for confirmation', None)), ('preauth', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Pre-authorized', None)), ('confirmed', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Confirmed', None)), ('rejected', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Rejected', None)), ('refunded', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Refunded', None)), ('error', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Error', None)), ('input', web_payments.translation._lazy_constant(('web_payments.translation.translation', 'gettext'), 'Input', None))], default='waiting', max_length=10),
        ),
        migrations.AddField(
            model_name='source',
            name='token',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='source',
            name='total',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='source',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='source',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='order.Order', verbose_name='Order'),
        ),
    ]
